### PR TITLE
Add option to build the certificates using docker

### PR DESCRIPTION
**Pull request by xoseperez**
* Adds a convenient way to build the certificates using docker (and avoid installing other dependencies on the host).
* Adds a convenient HOSTS setting to modify the `hosts` keys in the `certificate.json` files
* Can be included in the ChirpStack stack (https://github.com/chirpstack/chirpstack-docker) to auto-create the certificates and share them across the different services.

### CODE REVIEW

**Comment by brocaar** [comment]
Thanks for your pull-request. Some general feedback:

I would prefer if we would use a Docker image which already includes `cfssl`. I believe `alpine:edge` should already do (for this purpose I'm fine with using the `edge` tag). I think this makes it easier to maintain.

Can we take the entrypoint script to update the hostnames out of Docker? I would prefer when the functionality of Docker / non-Docker is the same. Now to automatically set the hosts, you must use Docker. I would prefer if we can move this to a make command, e.g. `HOSTS=localhost,127.0.0.1 make set-hosts && make`. I'm fine if the `make set-hosts` would call a shell script, but this way the Docker environment only provides the dependencies and does not add additional "magic".

**Comment by xoseperez** [comment]
Hi
Moved the hosts configuration outside docker as suggested, but couldn't find a base image with cfssl included (alpine:edge does not and neither has packages for it).

**Comment by xoseperez** [comment]
Any update on this?

**Comment by brocaar** [comment]
@xoseperez I have made some changes to this pull-request, please see the above commit.

There is one concern that I previously overlooked, it updates all the server certificates to the same set of hostnames. Usually this is not the case, e.g. the MQTT broker uses `mqtt.example.com`, the AS `lns.example.com` and the NS (for passive-roaming interface) `ns.example.com`.

Then the example certificate configuration contains config for two NSes (to demonstrate how to generate certificates for two NSes that are in a roaming agreement). This also would have a different hostname than the other services.

The only way to deal with this currently is make all the certificates usable for all the hostnames. Maybe for testing that is fine, but I would not advice this for production purposes.

**Comment by xoseperez** [comment]
I understand. Since there is a limited number of options (even if having different roaming agreements) we could programmatically add settings for each of them and a default to the existing $HOSTS variables. The `set-hosts.sh` file below would take care of that, so the user could do:

```
HOSTS="127.0.0.1,localhost,lns.example.com" make set-hosts
HOSTS="127.0.0.1,localhost,lns.example.com" MQTT_HOSTS="127.0.0.1,localhost,mqtt.example.com" make set-hosts
```
I know it's kind of verbose, maybe in a docker-compose file looks better. The available configuration settings are taken from the folder structure and would be:

```
GATEWAY_BRIDGE_BASICSTATION_HOSTS
APPLICATION_SERVER_API_HOSTS
APPLICATION_SERVER_JOIN_API_HOSTS
NETWORK_SERVER_API_HOSTS
NETWORK_SERVER_ROAMING_000000_HOSTS
NETWORK_SERVER_ROAMING_000001_HOSTS
...
MQTT_HOSTS
```
If for any of the services the corresponding setting is not defined it will use the default HOSTS value.

Code below. I have not commited it yet, waiting for your feedback

```
#!/bin/sh

# -----------------------------------------------------------------------------
# Defaults
# -----------------------------------------------------------------------------

HOSTS=${HOSTS:-"127.0.0.1,localhost"}
echo "Configuring certificates for $HOSTS"

# -----------------------------------------------------------------------------
# Modify certificate.json files
# -----------------------------------------------------------------------------

hosts_for_service() {

    local SERVICE=$1
    local HOSTS_FOR_SERVICE=$(eval echo \$$SERVICE)
    local HOSTS=${HOSTS_FOR_SERVICE:-$HOSTS}
    echo "$HOSTS"

}

command_from_hosts() {
    
    local HOSTS=$1

    local INDEX=0
    local COMMAND=".hosts=[]"
    local HOSTS_LIST=$(echo ${HOSTS} | sed -n 1'p' | tr ',' '\n')
    
    for HOST in ${HOSTS_LIST}
    do
        COMMAND="${COMMAND} | .hosts[${INDEX}]=\"${HOST}\""
        INDEX=$(( ${INDEX} + 1 ))
    done

    echo "$COMMAND"

}

for FOLDER in `find config -name server -type d`
do
    SERVICE=$(echo $FOLDER | sed 's/[-\/]/_/g' | tr 'a-z' 'A-Z' | sed 's/_SERVER$/_HOSTS/' | sed 's/^CONFIG_//'  | sed 's/^CHIRPSTACK_//')
    HOSTS_FOR_SERVICE=$(hosts_for_service "$SERVICE")
    COMMAND=$(command_from_hosts "$HOSTS_FOR_SERVICE")
    echo "Changing hosts in $FOLDER with \"$HOSTS_FOR_SERVICE\""
    contents=$(eval jq \'${COMMAND}\' $FOLDER/certificate.json)
    echo "${contents}" > $FOLDER/certificate.json
done


```

**Comment by xoseperez** [comment]
The last commit does not change the original functionality, only adds the option to set the domain name per service. I hope it can be merged.

**Comment by xoseperez** [comment]
Any update on this? :smiley:

**Comment by brocaar** [comment]
@xoseperez I have made a couple of edits and pushed these to this commit.

**Pull request merged**
